### PR TITLE
Enable compatibility with non-quantized models

### PR DESCRIPTION
**Pull request by lucas-p-bernardes**
This way, it's possible to run the project with no quantized models.

### CODE REVIEW

**Comment by leonheldattoradex** [comment]
@lucasbernardestoradex I'll need a bit more explanation of what this is actually doing in the commit message. Where is the magic number coming from?

**Comment by lucas-p-bernardes** [comment]
@leonheldattoradex I added a description about why this change is necessary.

**Review by brunoaamello — CHANGES_REQUESTED** [review]
Hello @lucasbernardestoradex,

Sorry for the delay here.

While I don't believe this is a bad idea, this specific conversion is not uniform across all models.
In fact, most floating point models have inputs between `0.0` and `1.0`. This change maps the `int8` range in `-1.0` to `1.0`.

Pre-processing and post-processing will also vary between different models, even if they have the same application.

Therefore, such change would only make sense if accompanied by a compatible floating point model.

**Comment by lucas-p-bernardes** [comment]
@brunoaamello @leonheldattoradex In a comment on the code, I specified that this is valid for the MobileNet architecture. Is there still anything missing for the merge?

**Comment by leonheldattoradex** [comment]
I think it's descriptive enough now. If anyone else wants to use this with other models they can simply drop that normalization portion.

**Pull request merged**
