### PR TITLE
Enable NPU acceleration by default

### PR DESCRIPTION
**Pull request by lucas-p-bernardes**

### CODE REVIEW

**Comment by brunoaamello** [comment]
Hello @lucasbernardestoradex, thanks for this change.

I am not sure how this was incorrect in the first place.

**Review by brunoaamello — APPROVED** [review]
Hello @lucasbernardestoradex, thanks for this change.

I am not sure how this was incorrect in the first place.

**Comment by lucas-p-bernardes** [comment]
> Hello @lucasbernardestoradex, thanks for this change.
> 
> I am not sure how this was incorrect in the first place.

@brunoaamello It was correct on developer website. Maybe just forgotten.

**Comment by lucas-p-bernardes** [comment]
@leonheldattoradex Can you please merge this?

**Comment by leonheldattoradex** [comment]
@lucasbernardestoradex I think you mean "default" instead of "standard".

**Comment by lucas-p-bernardes** [comment]
@leonheldattoradex Yeah! I fixed this.

**Pull request merged**
